export const MEMBER_SIGNUP = "MEMBER_SIGNUP";
export const MEMBER_LOGIN = "MEMBER_LOGIN";
export const MEMBER_AUTH_SUCCESS = "MEMBER_AUTH_SUCCESS";
export const MEMBER_LOGOUT = "MEMBER_LOGOUT";
export const MEMBER_SET_PREFERENCE = "MEMBER_SET_PREFERENCE";
export const MEMBER_SET_PREFERENCE_SUCCESS = "MEMBER_SET_PREFERENCE_SUCCESS";
export const MEMBER_GET_USER_DATA = "MEMBER_GET_USER_DATA";
export const MEMBER_GET_USER_DATA_SUCCESS = "MEMBER_GET_USER_DATA_SUCCESS";
export const MEMBER_CHECK_STATE = "MEMBER_CHECK_STATE";
export const MEMBER_EDIT_PROFILE = "MEMBER_EDIT_PROFILE";
export const MEMBER_EDIT_PROFILE_SUCCESS = "MEMBER_EDIT_PROFILE_SUCCESS";
export const MEMBER_EDIT_PASSWORD = "MEMBER_EDIT_PASSWORD";
export const MEMBER_SEND_VERIFICATION = "MEMBER_SEND_VERIFICATION";
export const MEMBER_SEND_VERIFICATION_SUCCESS = "MEMBER_SEND_VERIFICATION_SUCCESS";
export const MEMBER_SET_RESPONSE = "MEMBER_SET_RESPONSE";
export const MEMBER_DELETE_RESPONSE = "MEMBER_DELETE_RESPONSE";
export const MEMBER_REFRESH_TOKEN = "MEMBER_REFRESH_TOKEN";
export const MEMBER_SET_BOOKMARK = "MEMBER_SET_BOOKMARK";
export const MEMBER_SET_BOOKMARK_SUCCESS = "MEMBER_SET_BOOKMARK_SUCCESS";
export const MEMBER_GET_BOOKMARK_IDS = "MEMBER_GET_BOOKMARK_IDS";
export const MEMBER_GET_BOOKMARK_IDS_SUCCESS = "MEMBER_GET_BOOKMARK_IDS_SUCCESS";

export const COFFEE_SHOP_GET = "COFFEE_SHOP_GET";
export const COFFEE_SHOP_SET = "COFFEE_SHOP_SET";
export const COFFEE_SHOP_SET_LOADING = "COFFEE_SHOP_SET_LOADING";
export const COFFEE_SHOP_ADD_REVIEW = "COFFEE_SHOP_ADD_REVIEW";
export const COFFEE_SHOP_GET_REVIEWS = "COFFEE_SHOP_GET_REVIEWS";
export const COFFEE_SHOP_SET_REVIEWS = "COFFEE_SHOP_SET_REVIEWS";

export const COFFEE_SHOP_ADD = "COFFEE_SHOP_ADD";
export const COFFEE_SHOP_SET_DATA_SUCCESS = "COFFEE_SHOP_SET_DATA_SUCCESS";
export const COFFEE_SHOP_GET_DATA_SUCCESS = "COFFEE_SHOP_GET_DATA_SUCCESS";
export const COFFEE_SHOP_GET_BOOKMARK = "COFFEE_SHOP_GET_BOOKMARK";
export const COFFEE_SHOP_GET_BOOKMARK_SUCCESS = "COFFEE_SHOP_GET_BOOKMARK_SUCCESS";



